server:
  port: 8443
  ssl:
    key-store: ./ssl/sagademo.jks
    key-store-password: sagademo
    key-alias: sagademo
    key-store-type: JKS
  servlet:
    context-path: /apigateway
spring:
  security:
    csrf:
      enabled: false
# disable csrf for testing
security.enable-csrf: false      

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.springframework.security: debug      
# url of the entrypoint to the saga route
gateway:
  endpoint: "http://localhost:8084/loandemo/api/saga/route"