FROM registry.redhat.io/ubi9/openjdk-17-runtime:1.20

ENV JAVA_OPTIONS -Xmx512m

EXPOSE 8080/tcp

USER $UID

WORKDIR /app

ADD target/sagaApiGateway*.jar /app/api-gateway.jar

CMD ["java", "-jar", "/app/api-gateway.jar"]