apiVersion: v1
data:
  application.yaml: |-
    server:
      port: 8443
      ssl:
        key-store: /app/certs/sagademo.jks
        key-store-password: sagademo
        key-alias: sagademo
        key-store-type: JKS
    spring:
      security:
        csrf:
          enabled: false
    gateway:
      endpoint: "http://create-loan:8080"
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: saga-loan-demo
