apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: create-loan
    app.kubernetes.io/component: create-loan
    app.kubernetes.io/instance: create-loan
    app.kubernetes.io/name: create-loan
    app.kubernetes.io/part-of: create-loan-app
  name: create-loan
  namespace: saga-loan-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: create-loan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: create-loan
        deployment: create-loan
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        image: create-loan
        imagePullPolicy: Always
        name: create-loan
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: quayio
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
