applicant:
  get:
    endpoint: "http://loan-demo-model:8080/applicant"
  update:
    endpoint: "http://loan-demo-model:8080/applicant"
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.springframework.security: debug
server:
  port: 8080
  servlet:
    context-path: /