FROM registry.redhat.io/ubi9/openjdk-17-runtime:1.20

ENV JAVA_OPTIONS -Xmx512m

EXPOSE 8080/tcp

USER $UID

WORKDIR /app

ADD target/loanService*.jar /app/loan-service.jar

CMD ["java", "-jar", "/app/loan-service.jar"]