camel:
  servlet:
    mapping:
      enabled: true
      context-path: /loandemo/api/*  
  lra:
    enabled: true
    coordinator-url: http://localhost:8080
    coordinator-context-path: /lra-coordinator    
    local-participant-url: http://localhost:${server.port}/loandemo/api
  service:
    lra.enabled: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true    
saga-demo:
  loan:
    create:
      endpoint: "http://localhost:8082/sagaloandemo/loan/createloan"
    delete:
      endpoint: "http://localhost:8082/sagaloandemo/loan/deleteloan"
  applicant:
    update-limit:
      endpoint: "http://localhost:8083/sagaloandemo/applicant/updateloanlimit"
  saga:
    route:
      endpoint: "http://localhost:8084/saga/route"
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.springframework.security: debug
# server configuration
server:
  port: 8084