FROM registry.redhat.io/ubi9/openjdk-17-runtime:1.20

ENV JAVA_OPTIONS -Xmx512m

EXPOSE 8080/tcp


USER $UID

WORKDIR /app

ADD target/loanDemoModel*.jar /app/loan-demo-model.jar

CMD ["java", "-jar", "/app/loan-demo-model.jar"]