FROM fedora/postgresql:latest

# Build dependency offline to streamline build
USER root

RUN mkdir /temp && \
    groupadd non-root-postgres-group && \
    useradd non-root-postgres-user --group non-root-postgres-group && \
    chown -R non-root-postgres-user:non-root-postgres-group /temp && \
    chmod 777 /temp

WORKDIR /temp

USER non-root-postgres-user