---
--- role and database
---
DROP SCHEMA IF EXISTS sagademo;
DROP DATABASE IF EXISTS sagademo;
DROP ROLE IF EXISTS sagademo;
CREATE ROLE sagademo;
ALTER ROLE sagademo WITH LOGIN;
ALTER USER sagademo WITH PASSWORD 'sagademo';
CREATE DATABASE sagademo OWNER sagademo;
\connect sagademo;
CREATE SCHEMA sagademo;
GRANT ALL PRIVILEGES ON DATABASE sagademo TO sagademo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sagademo TO sagademo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sagademo TO sagademo;
ALTER DEFAULT PRIVILEGES IN SCHEMA sagademo GRANT ALL PRIVILEGES ON TABLES TO sagademo;
ALTER DEFAULT PRIVILEGES IN SCHEMA sagademo GRANT USAGE ON SEQUENCES TO sagademo;
GRANT USAGE, CREATE ON SCHEMA sagademo TO sagademo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sagademo TO sagademo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sagademo TO sagademo;
ALTER DEFAULT PRIVILEGES IN SCHEMA sagademo GRANT ALL PRIVILEGES ON TABLES TO sagademo;
ALTER DEFAULT PRIVILEGES IN SCHEMA sagademo GRANT USAGE ON SEQUENCES TO sagademo;
---GRANT ALL PRIVILEGES ON DATABASE sagademo TO sagademo;
---GRANT ALL ON ALL TABLES IN SCHEMA sagademo TO sagademo;
---GRANT ALL ON ALL SEQUENCES IN SCHEMA sagademo TO sagademo;
