/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.acme.saga;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.stereotype.Component;
import org.openapitools.model.*;
import org.apache.camel.model.rest.RestBindingMode;
import org.apache.camel.Exchange;
import org.apache.camel.LoggingLevel;

@Component
public class DevelopersApi extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        

        /**
        GET /saga/applicant : searches applicants
        **/
        rest()
            .get("/saga/applicant")
                .description("searches applicants")
                .id("searchApplicantsApi")
                .produces("application/json")
                .outType(Loan[].class)
                .param()
                    .name("searchString")
                    .type(RestParamType.query)
                    .required(false)
                    .description("pass an optional search string for looking up loans")
                .endParam()
                .param()
                    .name("skip")
                    .type(RestParamType.query)
                    .required(false)
                    .description("number of records to skip for pagination")
                .endParam()
                .param()
                    .name("limit")
                    .type(RestParamType.query)
                    .required(false)
                    .description("maximum number of records to return")
                .endParam()
                .to("direct:searchApplicants");
        

        /**
        GET /saga/loan : searches loans
        **/
        rest()
            .get("/saga/loan")
                .description("searches loans")
                .id("searchLoansApi")
                .produces("application/json")
                .outType(Loan[].class)
                .param()
                    .name("searchString")
                    .type(RestParamType.query)
                    .required(false)
                    .description("pass an optional search string for looking up loans")
                .endParam()
                .param()
                    .name("skip")
                    .type(RestParamType.query)
                    .required(false)
                    .description("number of records to skip for pagination")
                .endParam()
                .param()
                    .name("limit")
                    .type(RestParamType.query)
                    .required(false)
                    .description("maximum number of records to return")
                .endParam()
                .to("direct:searchLoans");
        
        from("direct:searchApplicants")
            .process( exchange -> {
                log.info("searchApplicants-> searchString: " + exchange.getIn().getHeader("searchString"));
                exchange.getIn().setHeader(Exchange.HTTP_RESPONSE_CODE, constant(201));
            })
            .log("Search applicants invoked...");

        from("direct:searchLoans")
            .log("Search loans invoked...");           
    }
}
