#FROM docker.io/arm64v8/postgres:12-alpine3.19
FROM amd64/postgres:12-alpine3.19

# Build dependency offline to streamline build
USER root

RUN mkdir /temp && \
    addgroup -S non-root-postgres-group && \
    adduser -S non-root-postgres-user -G non-root-postgres-group && \
    chown -R non-root-postgres-user:non-root-postgres-group /temp && \
    chmod 777 /temp

WORKDIR /temp

USER non-root-postgres-user