FROM registry.redhat.io/ubi9/openjdk-17-runtime:1.20

ENV JAVA_OPTIONS -Xmx512m

EXPOSE 8080/tcp

WORKDIR /app

ADD target/applicantService*.jar /app/applicant-service.jar

CMD ["java", "-jar", "/app/applicant-service.jar"]